management:
  context-path: /admin

server:
  port: 8080

guestbook:
  version: 1.1
  backend:
    redis:
      read:
        vip: localhost
        port: 6379
      write:
        vip: localhost
        port: 6379