version: '2'
services:
  frontend:
    image: nginx:stable-alpine
    ports:
    - "8081:80"
    volumes:
    - ./guestbook-simple-frontend/src/main/html:/etc/nginx/html:ro
    - ./guestbook-simple-frontend/src/main/config/nginx-base.conf:/etc/nginx/nginx.conf:ro
  gateway:
    build: ./guestbook-gateway-service/
    ports:
    - "8080:8080"
    environment:
      GATEWAY_GUESTBOOK_ENDPOINTSASSTRING: "restserver:8080"
      GATEWAY_FILTER_ENDPOINTSASSTRING: "filterserver:8080"
#    command: /deployments/run-java.sh --gateway.guestbook.endPointsAsString=restserver:8080 --gateway.filter.endPointsAsString=filterserver:8080
    depends_on:
    - storage
    - filter
  storage:
    build: ./guestbook-storage-service/
    ports:
    - "8085:8080"
    environment:
      GUESTBOOK_BACKEND_REDIS_READ_VIP: redis
      GUESTBOOK_BACKEND_REDIS_WRITE_VIP: redis
    depends_on:
    - redis
#    command: /deployments/run-java.sh --guestbook.backend.redis.read.vip=redis --guestbook.backend.redis.write.vip=redis
  filter:
    build: ./guestbook-filter-service/
    ports:
    - "8086:8080"
  redis:
    image: redis:3-alpine
