version: '2'
services:
  frontend:
    image: looztra/guestbook-simple-frontend:0.5.0-confd
    ports:
    - "8081:80"
    environment:
      GUESTBOOK_FRONTEND_API_SERVER_ROOT_URL: http://localhost:8080
  gatewayserver:
    image: looztra/guestbook-gateway:0.5.0-no-confd
    ports:
    - "8080:8080"
    environment:
      GATEWAY_GUESTBOOK_ENDPOINTSASSTRING: "restserver:8080"
      GATEWAY_FILTER_ENDPOINTSASSTRING: "filterserver:8080"
    depends_on:
    - restserver
    - filterserver
  restserver:
    image: looztra/guestbook-service-server:0.5.0-no-confd
    ports:
    - "8085:8080"
    environment:
      GUESTBOOK_BACKEND_REDIS_READ_VIP: redis
      GUESTBOOK_BACKEND_REDIS_WRITE_VIP: redis
    depends_on:
    - redis
  filterserver:
    image: looztra/guestbook-filter:0.5.0-no-confd
    ports:
    - "8086:8080"
  redis:
    image: redis:3-alpine
