---
apiVersion: v1
kind: Service
metadata:
  name: filter
  namespace: sandbox
  labels:
    app: filter
    product: guestbook
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: filter
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: filter
  namespace: sandbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: filter
        product: guestbook
    spec:
      containers:
      - name: filter
        image: looztra/guestbook-filter:0.5.0-no-confd
        ports:
        - containerPort: 8080