---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: sandbox
  labels:
    app: frontend
    product: guestbook
spec:
  type: NodePort
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: frontend
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
  namespace: sandbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: frontend
        product: guestbook
    spec:
      containers:
      - name: frontend
        image: looztra/guestbook-simple-frontend:0.5.0-confd
        ports:
        - containerPort: 80
        env:
        - name: GUESTBOOK_FRONTEND_API_SERVER_ROOT_URL
          value: "http://192.168.99.101:32179"
