---
apiVersion: v1
kind: Service
metadata:
  name: gateway
  namespace: sandbox
  labels:
    app: gateway
    product: guestbook
spec:
  type: NodePort
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: gateway
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: gateway
  namespace: sandbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: gateway
        product: guestbook
    spec:
      containers:
      - name: gateway
        image: looztra/guestbook-gateway:0.5.0-no-confd
        ports:
        - containerPort: 8080
        env:
        - name: GATEWAY_GUESTBOOK_ENDPOINTSASSTRING
          value: "service-api:8080"
        - name: GATEWAY_FILTER_ENDPOINTSASSTRING
          value: "filter:8080"