---
apiVersion: v1
kind: Service
metadata:
  name: redis
  namespace: sandbox
  labels:
    app: redis
    product: guestbook
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: redis
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: redis
  namespace: sandbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: redis
        product: guestbook
    spec:
      containers:
      - name: redis
        image: redis:3-alpine
        ports:
        - containerPort: 6379