---
apiVersion: v1
kind: Service
metadata:
  name: service-api
  namespace: sandbox
  labels:
    app: service-api
    product: guestbook
spec:
  ports:
  - port: 8080
    protocol: TCP
  selector:
    app: service-api
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: service-api
  namespace: sandbox
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: service-api
        product: guestbook
    spec:
      containers:
      - name: service-api
        image: looztra/guestbook-service-server:0.5.0-no-confd
        ports:
        - containerPort: 8080
        env:
        - name: GUESTBOOK_BACKEND_REDIS_READ_VIP
          value: "redis"
        - name: GUESTBOOK_BACKEND_REDIS_WRITE_VIP
          value: "redis"